[package]
name = "kurama-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
futures-core.workspace = true
futures-util.workspace = true
getrandom.workspace = true
kurama-protocol = { path = "../kurama-protocol" }
serde_json.workspace = true
tokio.workspace = true
