mod activity;
mod agents;
mod approval;
mod backend;
mod composer;
mod input;
mod layout;
mod onboarding;
mod render;
mod state;
mod transcript;

pub use activity::activity_line;
pub use agents::{AgentRow, sort_agents};
pub use approval::ApprovalState;
pub(crate) use backend::{CursorTrackingBackend, SharedBackend};
pub(crate) use composer::{approval_height, composer_height};
pub use input::{TerminalGuard, spawn_input_thread};
pub use layout::ResponsiveLayout;
pub(crate) use layout::{main_area, visible_activity_rect};
pub use onboarding::{OnboardingState, OnboardingSubmission};
pub(crate) use render::SURFACE;
pub use render::render;
pub use state::{ActivityState, Overlay, ToolLifecycle, ToolTranscript, TranscriptEntry, TuiState};
pub use transcript::{TranscriptDetail, transcript_lines};
